"""
Module for creating synthetic data for human names

Names were generated by using claude.ai using the prompt
(prompts were following with the project context):
"Can you generate me a list of first names with different cultural backgrounds in a python list containing 100000 elements"
"""

import random

# Base first names from different cultural backgrounds
first_names_by_culture = {
    # European first names
    'english_male': ['James', 'John', 'Robert', 'Michael', 'William', 'David', 'Richard', 'Joseph', 'Thomas', 'Christopher',
                     'Charles', 'Daniel', 'Matthew', 'Anthony', 'Mark', 'Donald', 'Steven', 'Paul', 'Andrew', 'Joshua',
                     'Kenneth', 'Kevin', 'Brian', 'George', 'Edward', 'Ronald', 'Timothy', 'Jason', 'Jeffrey', 'Ryan'],
    
    'english_female': ['Mary', 'Patricia', 'Jennifer', 'Linda', 'Elizabeth', 'Barbara', 'Susan', 'Jessica', 'Sarah', 'Karen',
                       'Nancy', 'Lisa', 'Betty', 'Helen', 'Sandra', 'Donna', 'Carol', 'Ruth', 'Sharon', 'Michelle',
                       'Laura', 'Sarah', 'Kimberly', 'Deborah', 'Dorothy', 'Lisa', 'Nancy', 'Karen', 'Betty', 'Helen'],
    
    'spanish_male': ['Jose', 'Luis', 'Carlos', 'Juan', 'Antonio', 'Miguel', 'Angel', 'Francisco', 'Manuel', 'Ricardo',
                     'Fernando', 'Daniel', 'Jorge', 'Alejandro', 'Rafael', 'Jesus', 'Roberto', 'Pedro', 'Pablo', 'Diego',
                     'Sergio', 'Andres', 'Javier', 'Eduardo', 'Arturo', 'Raul', 'Hector', 'Enrique', 'Guillermo', 'Marco'],
    
    'spanish_female': ['Maria', 'Carmen', 'Ana', 'Isabel', 'Dolores', 'Pilar', 'Teresa', 'Rosa', 'Francisca', 'Antonia',
                       'Mercedes', 'Josefa', 'Concepcion', 'Manuela', 'Rosario', 'Juana', 'Encarnacion', 'Esperanza', 'Angeles', 'Cristina',
                       'Luz', 'Consuelo', 'Amparo', 'Remedios', 'Soledad', 'Montserrat', 'Asuncion', 'Nieves', 'Milagros', 'Rocio'],
    
    'italian_male': ['Giuseppe', 'Antonio', 'Marco', 'Francesco', 'Mario', 'Luigi', 'Andrea', 'Stefano', 'Angelo', 'Vincenzo',
                     'Alessandro', 'Roberto', 'Giovanni', 'Salvatore', 'Domenico', 'Pietro', 'Nicola', 'Paolo', 'Michele', 'Luca',
                     'Matteo', 'Davide', 'Simone', 'Federico', 'Riccardo', 'Fabio', 'Massimo', 'Claudio', 'Emanuele', 'Daniele'],
    
    'italian_female': ['Maria', 'Anna', 'Giuseppina', 'Rosa', 'Angela', 'Giovanna', 'Teresa', 'Lucia', 'Carmela', 'Caterina',
                       'Antonietta', 'Francesca', 'Paola', 'Giulia', 'Elisabetta', 'Alessandra', 'Chiara', 'Federica', 'Roberta', 'Valentina',
                       'Silvia', 'Daniela', 'Patrizia', 'Monica', 'Antonella', 'Stefania', 'Cristina', 'Simona', 'Claudia', 'Barbara'],
    
    'german_male': ['Hans', 'Klaus', 'Peter', 'Wolfgang', 'Helmut', 'Walter', 'Manfred', 'Gerhard', 'Horst', 'Dieter',
                    'Jurgen', 'Gunter', 'Frank', 'Bernd', 'Rainer', 'Uwe', 'Andreas', 'Thomas', 'Michael', 'Stefan',
                    'Heinrich', 'Werner', 'Gunther', 'Karl', 'Hermann', 'Otto', 'Friedrich', 'Georg', 'Ernst', 'Wilhelm'],
    
    'german_female': ['Ursula', 'Ingrid', 'Maria', 'Helga', 'Gisela', 'Monika', 'Barbara', 'Elisabeth', 'Brigitte', 'Christa',
                      'Hannelore', 'Petra', 'Sabine', 'Gabriele', 'Renate', 'Susanne', 'Angelika', 'Birgit', 'Claudia', 'Martina',
                      'Margot', 'Gudrun', 'Irmgard', 'Waltraud', 'Rosemarie', 'Karin', 'Doris', 'Anneliese', 'Sigrid', 'Edith'],
    
    'french_male': ['Jean', 'Pierre', 'Michel', 'Andre', 'Philippe', 'Alain', 'Bernard', 'Roger', 'Henri', 'Marcel',
                    'Christian', 'Daniel', 'Patrick', 'Robert', 'Paul', 'Jacques', 'Claude', 'Gerard', 'Rene', 'Louis',
                    'Antoine', 'Nicolas', 'Francois', 'Julien', 'Alexandre', 'Sebastien', 'Olivier', 'Christophe', 'Laurent', 'Pascal'],
    
    'french_female': ['Marie', 'Francoise', 'Monique', 'Catherine', 'Nathalie', 'Isabelle', 'Sylvie', 'Martine', 'Nicole', 'Christiane',
                      'Jacqueline', 'Chantal', 'Dominique', 'Brigitte', 'Jeanne', 'Pascale', 'Veronique', 'Michelle', 'Christine', 'Corinne',
                      'Sophie', 'Sandrine', 'Valerie', 'Stephanie', 'Aurelie', 'Celine', 'Emilie', 'Camille', 'Manon', 'Lea'],
    
    # Asian first names
    'chinese_male': ['Wei', 'Jun', 'Ming', 'Qiang', 'Lei', 'Tao', 'Jian', 'Peng', 'Bin', 'Yong',
                     'Hao', 'Gang', 'Fei', 'Bo', 'Kai', 'Cheng', 'Yang', 'Dong', 'Hui', 'Rui',
                     'Xin', 'Lin', 'Xiong', 'Jie', 'Liang', 'Feng', 'Hua', 'Qing', 'Zhi', 'Long'],
    
    'chinese_female': ['Li', 'Mei', 'Ling', 'Yan', 'Xiu', 'Min', 'Jing', 'Hong', 'Ping', 'Fang',
                       'Xia', 'Lan', 'Ying', 'Qin', 'Yun', 'Ning', 'Rong', 'Xue', 'Yu', 'Juan',
                       'Xiang', 'Hui', 'Qian', 'Jin', 'Shu', 'Zhen', 'Miao', 'Xin', 'Dan', 'Shan'],
    
    'japanese_male': ['Hiroshi', 'Takeshi', 'Satoshi', 'Masahiro', 'Kazuhiro', 'Kenji', 'Yuji', 'Naoki', 'Takashi', 'Akira',
                      'Daisuke', 'Ryouta', 'Yuki', 'Shingo', 'Kenta', 'Shinji', 'Makoto', 'Tetsuya', 'Koji', 'Tomoya',
                      'Hideki', 'Yoshiaki', 'Masaki', 'Taro', 'Jiro', 'Ichiro', 'Saburo', 'Shiro', 'Goro', 'Hachiro'],
    
    'japanese_female': ['Yuki', 'Akiko', 'Keiko', 'Naoko', 'Yoko', 'Michiko', 'Sachiko', 'Hiroko', 'Kumiko', 'Tomoko',
                        'Emi', 'Mayumi', 'Ayako', 'Noriko', 'Kazuko', 'Mariko', 'Junko', 'Satomi', 'Megumi', 'Yukiko',
                        'Miyuki', 'Masako', 'Reiko', 'Takako', 'Shizuko', 'Yoshiko', 'Teruko', 'Hanako', 'Midori', 'Emiko'],
    
    'korean_male': ['Min-jun', 'Min-ho', 'Joon-ho', 'Hyun-woo', 'Seung-woo', 'Ji-hoon', 'Sung-min', 'Dong-hyun', 'Hyun-soo', 'Jun-ho',
                    'Tae-hyun', 'Sang-hyun', 'Jin-woo', 'Kyung-ho', 'Seong-ho', 'Young-ho', 'Jae-hyun', 'Woo-jin', 'Chang-min', 'Seung-ho'],
    
    'korean_female': ['So-young', 'Min-jung', 'Soo-jin', 'Hye-jin', 'Ji-young', 'Eun-jung', 'Jung-min', 'Soo-yeon', 'Hye-young', 'Yu-jin',
                      'Mi-young', 'Kyung-mi', 'Sun-hee', 'Yeon-hee', 'Mi-kyung', 'Jeong-eun', 'Yoo-jin', 'Hye-won', 'Soo-jung', 'Eun-hee'],
    
    'indian_male': ['Rajesh', 'Suresh', 'Ramesh', 'Mahesh', 'Dinesh', 'Mukesh', 'Naresh', 'Rakesh', 'Umesh', 'Girish',
                    'Anil', 'Sunil', 'Ashok', 'Vinod', 'Manoj', 'Sanjay', 'Ajay', 'Vijay', 'Ravi', 'Amit',
                    'Arjun', 'Karan', 'Rohan', 'Nikhil', 'Rahul', 'Ankit', 'Harsh', 'Varun', 'Abhinav', 'Gaurav'],
    
    'indian_female': ['Priya', 'Pooja', 'Sunita', 'Anita', 'Kavita', 'Meera', 'Geeta', 'Radha', 'Sita', 'Lata',
                      'Shanti', 'Kamala', 'Sharda', 'Usha', 'Rekha', 'Asha', 'Nisha', 'Ritu', 'Neha', 'Seema',
                      'Preeti', 'Swati', 'Shruti', 'Sneha', 'Shweta', 'Divya', 'Anjali', 'Nikita', 'Simran', 'Riya'],
    
    # African first names
    'african_male': ['Kwame', 'Kofi', 'Yaw', 'Akwasi', 'Kwaku', 'Kwadwo', 'Kwabena', 'Kojo', 'Kweku', 'Ama',
                     'Abdi', 'Amari', 'Bakari', 'Jabari', 'Jengo', 'Kesi', 'Omari', 'Sekai', 'Tau', 'Zuberi',
                     'Jomo', 'Kgosi', 'Lerato', 'Mandla', 'Nkosana', 'Sipho', 'Thabo', 'Tshepo', 'Vuyo', 'Xolani'],
    
    'african_female': ['Akosua', 'Adwoa', 'Afia', 'Akua', 'Yaa', 'Efua', 'Ama', 'Abena', 'Esi', 'Adjoa',
                       'Amina', 'Asha', 'Fatima', 'Halima', 'Khadija', 'Mariam', 'Nuru', 'Safiya', 'Zahara', 'Zeinab',
                       'Boipelo', 'Dineo', 'Kagiso', 'Kefilwe', 'Lesego', 'Mpho', 'Naledi', 'Oratile', 'Palesa', 'Tebogo'],
    
    # Middle Eastern first names
    'arabic_male': ['Ahmed', 'Mohammed', 'Ali', 'Hassan', 'Hussein', 'Omar', 'Khalil', 'Farid', 'Rashid', 'Mansour',
                    'Habib', 'Nasser', 'Salim', 'Karim', 'Zaki', 'Fouad', 'Samir', 'Tariq', 'Jamal', 'Youssef',
                    'Mustafa', 'Ibrahim', 'Mahmoud', 'Abdallah', 'Saleh', 'Faisal', 'Waleed', 'Hamid', 'Salam', 'Adel'],
    
    'arabic_female': ['Fatima', 'Aisha', 'Maryam', 'Zainab', 'Khadija', 'Amina', 'Leila', 'Nour', 'Yasmin', 'Rania',
                      'Nadia', 'Samira', 'Layla', 'Huda', 'Rana', 'Dina', 'Lina', 'Maya', 'Reem', 'Farah',
                      'Zara', 'Salma', 'Hala', 'Iman', 'Nora', 'Rima', 'Yara', 'Dania', 'Lama', 'Sana'],
    
    # Scandinavian first names
    'scandinavian_male': ['Lars', 'Erik', 'Nils', 'Olav', 'Magnus', 'Bjorn', 'Knut', 'Arne', 'Gunnar', 'Rune',
                          'Andreas', 'Thomas', 'Morten', 'Jon', 'Christian', 'Daniel', 'Martin', 'Fredrik', 'Johan', 'Mikael',
                          'Axel', 'Emil', 'Oscar', 'Viktor', 'Filip', 'Hugo', 'Ludvig', 'Theodor', 'Edvin', 'Linus'],
    
    'scandinavian_female': ['Astrid', 'Ingrid', 'Solveig', 'Sigrid', 'Gunnhild', 'Ragnhild', 'Marit', 'Kari', 'Tone', 'Liv',
                           'Anne', 'Inger', 'Berit', 'Kristin', 'Marianne', 'Hanne', 'Camilla', 'Lise', 'Randi', 'Bente',
                           'Emma', 'Alma', 'Ella', 'Olivia', 'Saga', 'Maja', 'Elsa', 'Wilma', 'Lilly', 'Astrid'],
    
    # Slavic first names
    'slavic_male': ['Alexander', 'Vladimir', 'Sergey', 'Dmitry', 'Andrey', 'Alexey', 'Nikolay', 'Ivan', 'Mikhail', 'Yuri',
                    'Pavel', 'Oleg', 'Viktor', 'Anatoly', 'Vasily', 'Boris', 'Gennady', 'Leonid', 'Valery', 'Evgeny',
                    'Petr', 'Jan', 'Tomas', 'Pavel', 'Michal', 'Lukas', 'Jakub', 'Ondrej', 'Vaclav', 'Martin'],
    
    'slavic_female': ['Olga', 'Tatyana', 'Irina', 'Elena', 'Svetlana', 'Natalya', 'Galina', 'Lyudmila', 'Valentina', 'Anna',
                      'Maria', 'Larisa', 'Oksana', 'Ekaterina', 'Yulia', 'Alla', 'Nina', 'Vera', 'Lyubov', 'Raisa',
                      'Jana', 'Petra', 'Hana', 'Jitka', 'Lenka', 'Tereza', 'Barbora', 'Klara', 'Veronika', 'Kristyna'],
    
    # Other cultures
    'irish_male': ['Liam', 'Sean', 'Conor', 'Aiden', 'Cian', 'Oisin', 'Darragh', 'Niall', 'Eoin', 'Ruairi',
                   'Padraig', 'Ciaran', 'Ronan', 'Colm', 'Donal', 'Eamon', 'Fionntan', 'Cathal', 'Declan', 'Kieran'],
    
    'irish_female': ['Aoife', 'Siobhan', 'Niamh', 'Ciara', 'Aisling', 'Mairead', 'Caoimhe', 'Orla', 'Sinead', 'Grainne',
                     'Deirdre', 'Brigid', 'Nora', 'Maeve', 'Fiona', 'Roisin', 'Clodagh', 'Saoirse', 'Ailbhe', 'Muirenn'],
    
    'jewish_male': ['David', 'Daniel', 'Michael', 'Joshua', 'Benjamin', 'Jacob', 'Samuel', 'Aaron', 'Noah', 'Isaac',
                    'Elijah', 'Gabriel', 'Caleb', 'Nathan', 'Jonathan', 'Adam', 'Ethan', 'Levi', 'Seth', 'Asher'],
    
    'jewish_female': ['Sarah', 'Rebecca', 'Rachel', 'Leah', 'Miriam', 'Esther', 'Hannah', 'Abigail', 'Naomi', 'Ruth',
                      'Judith', 'Deborah', 'Tamar', 'Rivka', 'Chaya', 'Malka', 'Shoshana', 'Yael', 'Tova', 'Simcha'],
    
    'greek_male': ['Georgios', 'Ioannis', 'Konstantinos', 'Dimitrios', 'Nikolaos', 'Panagiotis', 'Vasileios', 'Christos', 'Athanasios', 'Michail',
                   'Alexandros', 'Stefanos', 'Evangelos', 'Spyridon', 'Antonios', 'Theodoros', 'Grigorios', 'Charalampos', 'Andreas', 'Kostas'],
    
    'greek_female': ['Maria', 'Eleni', 'Aikaterini', 'Vasiliki', 'Sophia', 'Angeliki', 'Georgia', 'Dimitra', 'Konstantina', 'Ioanna',
                     'Paraskevi', 'Fotini', 'Evangelia', 'Chrysoula', 'Eftychia', 'Styliani', 'Anastasia', 'Kyriaki', 'Despoina', 'Antonia']
}

def generate_first_names_list(target_size=100000):
    """Generate a list of first names with diverse cultural backgrounds."""
    first_names = []
    
    # Get all name lists
    all_name_lists = list(first_names_by_culture.values())
    total_lists = len(all_name_lists)
    
    # Calculate how many names we need from each list
    base_per_list = target_size // total_lists
    
    # Add names from each cultural list
    for name_list in all_name_lists:
        for _ in range(base_per_list):
            first_names.append(random.choice(name_list))
    
    # Fill remaining spots to reach exact target size
    remaining = target_size - len(first_names)
    for _ in range(remaining):
        name_list = random.choice(all_name_lists)
        first_names.append(random.choice(name_list))
    
    # Shuffle the final list to mix cultures and genders
    random.shuffle(first_names)
    
    return first_names

# Generate the list of 100,000 first names
first_names_list = generate_first_names_list(100000)

