"""
Module for creating synthetic data for human names

Names were generated by using claude.ai using the prompt:
"Can you generate me a list of Surnames with different cultural backgrounds in a python list containing 100000 elements"
"""

import random

# Base surnames from different cultural backgrounds
surnames_by_region = {
    # European surnames
    'english': ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez', 
                'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
                'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson'],
    
    'spanish': ['Rodriguez', 'Martinez', 'Garcia', 'Lopez', 'Gonzalez', 'Hernandez', 'Perez', 'Sanchez', 'Ramirez', 'Cruz',
                'Flores', 'Gomez', 'Diaz', 'Reyes', 'Morales', 'Ortiz', 'Gutierrez', 'Chavez', 'Ramos', 'Castillo',
                'Herrera', 'Ruiz', 'Alvarez', 'Vargas', 'Romero', 'Torres', 'Jimenez', 'Mendoza', 'Medina', 'Aguilar'],
    
    'italian': ['Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco',
                'Bruno', 'Gallo', 'Conti', 'DeLuca', 'Mancini', 'Costa', 'Giordano', 'Rizzo', 'Lombardi', 'Moretti',
                'Barbieri', 'Fontana', 'Santoro', 'Mariani', 'Rinaldi', 'Caruso', 'Ferrara', 'Galli', 'Martini', 'Leone'],
    
    'german': ['Mueller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer', 'Wagner', 'Becker', 'Schulz', 'Hoffmann',
               'Schaefer', 'Koch', 'Bauer', 'Richter', 'Klein', 'Wolf', 'Schroeder', 'Neumann', 'Schwarz', 'Zimmermann',
               'Braun', 'Krueger', 'Hartmann', 'Lange', 'Schmitt', 'Werner', 'Krause', 'Meier', 'Lehmann', 'Schmid'],
    
    'french': ['Martin', 'Bernard', 'Dubois', 'Thomas', 'Robert', 'Richard', 'Petit', 'Durand', 'Leroy', 'Moreau',
               'Simon', 'Laurent', 'Lefebvre', 'Michel', 'Garcia', 'David', 'Bertrand', 'Roux', 'Vincent', 'Fournier',
               'Morel', 'Girard', 'Andre', 'Lefevre', 'Mercier', 'Dupont', 'Lambert', 'Bonnet', 'Francois', 'Martinez'],
    
    # Asian surnames
    'chinese': ['Wang', 'Li', 'Zhang', 'Liu', 'Chen', 'Yang', 'Huang', 'Zhao', 'Wu', 'Zhou',
                'Xu', 'Sun', 'Ma', 'Zhu', 'Hu', 'Guo', 'He', 'Lin', 'Luo', 'Gao',
                'Zheng', 'Liang', 'Xie', 'Song', 'Tang', 'Xu', 'Deng', 'Han', 'Feng', 'Cao'],
    
    'japanese': ['Sato', 'Suzuki', 'Takahashi', 'Tanaka', 'Watanabe', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Kato',
                 'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi', 'Shimizu', 'Yamazaki',
                 'Mori', 'Abe', 'Ikeda', 'Hashimoto', 'Yamashita', 'Ishikawa', 'Nakajima', 'Maeda', 'Fujita', 'Ogawa'],
    
    'korean': ['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Kang', 'Cho', 'Yoon', 'Jang', 'Lim',
               'Han', 'Oh', 'Seo', 'Shin', 'Kwon', 'Hwang', 'Ahn', 'Kim', 'Song', 'Hong',
               'Chae', 'Go', 'Kwak', 'Yoo', 'Bae', 'Im', 'Huh', 'Noh', 'Seong', 'Moon'],
    
    'indian': ['Sharma', 'Verma', 'Singh', 'Kumar', 'Devi', 'Gupta', 'Agarwal', 'Yadav', 'Mishra', 'Tiwari',
               'Prasad', 'Jain', 'Sinha', 'Pandey', 'Shukla', 'Dubey', 'Agrawal', 'Srivastava', 'Tripathi', 'Chandra',
               'Banerjee', 'Mukherjee', 'Chakraborty', 'Ghosh', 'Bose', 'Chatterjee', 'Datta', 'Sengupta', 'Roy', 'Das'],
    
    # African surnames
    'african': ['Okafor', 'Adebayo', 'Osei', 'Mensah', 'Asante', 'Boateng', 'Darko', 'Opoku', 'Adjei', 'Frimpong',
                'Mwangi', 'Kariuki', 'Kamau', 'Wanjiku', 'Njoroge', 'Kiprotich', 'Cheruiyot', 'Kiprop', 'Rotich', 'Langat',
                'Dlamini', 'Nkomo', 'Sibanda', 'Moyo', 'Ndlovu', 'Mpofu', 'Ncube', 'Mahlangu', 'Khumalo', 'Phiri'],
    
    # Middle Eastern surnames
    'arabic': ['Al-Ahmad', 'Al-Hassan', 'Al-Hussein', 'Al-Rashid', 'Al-Mansour', 'Al-Zahra', 'Al-Malik', 'Al-Salim', 'Al-Nasser', 'Al-Sharif',
               'Mahmoud', 'Mohammed', 'Ahmed', 'Hassan', 'Ali', 'Omar', 'Khalil', 'Farid', 'Rashid', 'Mansour',
               'Habib', 'Nasser', 'Salim', 'Karim', 'Zaki', 'Fouad', 'Samir', 'Tariq', 'Jamal', 'Youssef'],
    
    # Scandinavian surnames
    'scandinavian': ['Andersen', 'Nielsen', 'Hansen', 'Pedersen', 'Kristensen', 'Larsen', 'Christensen', 'Paulsen', 'Johnsen', 'Knudsen',
                     'Johansson', 'Andersson', 'Karlsson', 'Nilsson', 'Eriksson', 'Larsson', 'Olsson', 'Persson', 'Svensson', 'Gustafsson',
                     'Berg', 'Lund', 'Dahl', 'Holm', 'Strand', 'Lindberg', 'Haugen', 'Bakke', 'Olsen', 'Moen'],
    
    # Slavic surnames
    'slavic': ['Novak', 'Svoboda', 'Novotny', 'Dvorak', 'Cerny', 'Prochazka', 'Krejci', 'Horak', 'Nemec', 'Polak',
               'Petrov', 'Ivanov', 'Smirnov', 'Kuznetsov', 'Popov', 'Sokolov', 'Lebedev', 'Kozlov', 'Novikov', 'Morozov',
               'Kowalski', 'Wisniewski', 'Wojcik', 'Kowalczyk', 'Kaminski', 'Lewandowski', 'Zielinski', 'Szymanski', 'Wozniak', 'Dabrowski'],
    
    # Other cultures
    'irish': ['Murphy', 'Kelly', 'Sullivan', 'Walsh', 'Smith', 'OBrien', 'Byrne', 'Ryan', 'OConnor', 'ONeill',
              'OReilly', 'Doyle', 'McCarthy', 'Gallagher', 'ODonnell', 'Lynch', 'Murray', 'Quinn', 'Moore', 'McLaughlin'],
    
    'jewish': ['Cohen', 'Levy', 'Miller', 'Goldstein', 'Friedman', 'Katz', 'Rosen', 'Goldberg', 'Klein', 'Schwartz',
               'Rosenberg', 'Stern', 'Weiss', 'Shapiro', 'Hoffman', 'Kaufman', 'Rubin', 'Berman', 'Steinberg', 'Silverman'],
    
    'dutch': ['De Jong', 'Jansen', 'De Vries', 'Van Der Berg', 'Van Dijk', 'Bakker', 'Janssen', 'Visser', 'Smit', 'Meijer',
              'Boer', 'Mulder', 'De Boer', 'De Groot', 'Bos', 'Vos', 'Peters', 'Hendriks', 'Van Leeuwen', 'Dekker'],
    
    'portuguese': ['Silva', 'Santos', 'Ferreira', 'Pereira', 'Oliveira', 'Costa', 'Rodrigues', 'Martins', 'Jesus', 'Sousa',
                   'Fernandes', 'Goncalves', 'Gomes', 'Lopes', 'Marques', 'Alves', 'Almeida', 'Ribeiro', 'Carvalho', 'Teixeira'],
    
    'greek': ['Papadopoulos', 'Georgiou', 'Dimitriou', 'Constantinides', 'Nikolaou', 'Ioannou', 'Christodoulou', 'Stylianou', 'Charalambous', 'Andreou',
              'Petrou', 'Savva', 'Hadjisavvas', 'Loizou', 'Michail', 'Demetriou', 'Kyriacou', 'Antoniou', 'Stavrou', 'Economou']
}

def generate_surnames_list(target_size=100000):
    """Generate a list of surnames with diverse cultural backgrounds."""
    surnames = []
    
    # Calculate how many surnames we need from each culture
    cultures = list(surnames_by_region.keys())
    base_per_culture = target_size // len(cultures)
    
    for culture, culture_surnames in surnames_by_region.items():
        # Add base surnames for this culture
        for _ in range(base_per_culture):
            surnames.append(random.choice(culture_surnames))
    
    # Fill remaining spots to reach exact target size
    remaining = target_size - len(surnames)
    for _ in range(remaining):
        culture = random.choice(cultures)
        surnames.append(random.choice(surnames_by_region[culture]))
    
    # Shuffle the final list to mix cultures
    random.shuffle(surnames)
    
    return surnames
